### ISSUE TITLE
Unable to find the Azure Function Zip file mentioned in the pre-requisites

### ISSUE THREAD

**Issue by nidhal-hafeez** [Azure/document-vector-pipeline#13]
The pre-requisite step number 4:
Download the Azure Functions zip file* from the [latest release](https://github.com/Azure/document-vector-pipeline/releases) (or build your own from this repo with dotnet publish -c Release, and then zip the resulting publish directory)
The link gives the message there' no release.

**Comment by Pilchie** [comment]
Thanks - we moved the source from another repo and the release happened there.  I'll look at getting it posted here.  In the meantime, you should be able to build the zip from the sources in this directory.

**Comment by Pilchie** [comment]
Hi - I created a new release that should contain the zip.  Please let us know if you have any issues.
